### PR TITLE
Separate CSS files

### LINKED ISSUE #34: Clean up CSS dependencies
Unsure of what Normalize.css is, incomplete version of main.css?

### PR DESCRIPTION
**Pull request by declansullivan**
Closes #34

### CODE REVIEW

**Comment by declansullivan** [comment]
This branch has some changes: Normalize.CSS is deleted, main.css has become Bootstrap.css, and anything clearly OI has been moved out of Bootstrap.css into OpenIonic.css.  The ejs files now directly link to normalize.css from its Github repo, instead of being copy pasted.

I would do this with OI and Bootstrap, but the previous team used large chunks and shuffled up the order of each, so it's difficult to know what to keep, and in my quick tests just linking to these things broke our view.  Also, OI separates all of their css files into separate folders, so we'd have a lot of links, and I do not know which the team used.

**Comment by sumeet-bansal** [comment]
How much work would it be to resolve the breaks caused by linking to the hosted CSS files?

**Comment by declansullivan** [comment]
I already gave it a go by linking directly with all of them and the CSS was all busted, there might be extra bits included in main.css or different portions used but since there's 7500 lines I wasn't all that interested in going through it and comparing it all.

**Comment by declansullivan** [comment]
Closing this, a new one will be made very soon to work with our new structure.

**Pull request closed without merging**
