### PR TITLE
Cleaner implementation for update-questions.js

### PR DESCRIPTION
**Pull request by jayrc7**

### CODE REVIEW

**Comment by sumeet-bansal** [comment]
Looks good! A couple notes:
1. `currentOptions` and `endOptions` are two separate arrays with corresponding indices right now, so using a [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) might make more sense since there's a direct link with key-value pairs that you don't get from corresponding indices. Plus, since Maps have constant-time lookup, a quick get operation can replace the loop.
```javascript
// something like this
const options = new Map([
  [1, 11],
  [8, 11],
  ...,
  [36, 40],
]);
currentNumber = options.has(currentNumber) ? options.get(currentNumber) ? -1;
```
2. It looks like the same elements are being selected and enabled/disabled, so instead of copying all those statements over twice in the `if-else`, we can move them outside the conditional and set the attribute based on a boolean variable that's equivalent to the condition in the `if` statement.
```javascript
// for example, this snippet...
if ($('#No-'+ currentNumber).is(":checked")) {
  if (!reverseNumOptions && currentNumber == 1) {
    $('#0-4').attr("disabled", true);
  }
} else {
  if (!reverseNumOptions && currentNumber == 1) {
    $('#0-4').attr("disabled", null);
  }      
}

// ...can be refactored into this
const somethingIsChecked = $('#No-'+ currentNumber).is(":checked");
if (!reverseNumOptions && currentNumber == 1) {
  $('#0-4').attr("disabled", somethingIsChecked);
}
```

**Comment by jayrc7** [comment]
Made the changes to the code, thanks for the solid feedback

**Comment by sumeet-bansal** [comment]
Nice work!

**Comment by sumeet-bansal** [comment]
@jayrc7 nice work!

**Pull request merged**
