### PR TITLE
Clean up CSS

### LINKED ISSUE #34: Clean up CSS dependencies
Unsure of what Normalize.css is, incomplete version of main.css?

### PR DESCRIPTION
**Pull request by declansullivan**
Closes #34.

### CODE REVIEW

**Comment by declansullivan** [comment]
Getting this done, by the looks of things main.css is made of Normalize and Open Ionic as you saw, but the rest of it seems to just be bootstrap.css from https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css.  Do you want me to rename main.css to bootstrap.css for consistency or just leave it as main.css?

**Comment by hahsu** [comment]
Instead of copying and pasting all of the code from https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css, isn't there a way to just link it? So like instead of having a whole css file dedicated to the code from bootstrap, we just link the already written bootstrap files to our html pages.

**Comment by declansullivan** [comment]
Oh that's way better, I'll give that a go, same for the open ionic stuff

**Comment by declansullivan** [comment]
After screwing around with linking to the stylesheets and all that, it doesn't seem like it's going to be the best idea.  When they put together main.css they really hodgepodged everything together so I'm not sure what gets used where.  I think the better option is the previous of having the bootstrap.css, OpenIonic.css, and Normalize.css.  They didn't even use all of the original bootstrap.css, only a large portion of it.

**Comment by declansullivan** [comment]
Okay, I've updated my secondary branch on this issue, I'll make a pull request with that one instead so that it's easier to keep track of.  In it I directly link to the normalize.css from Github, but anything related to OpenIonic is kept in our repo since their repo has everything separated out, and I do not know which of their files was used to build our main.css.  I also separated anything Bootstrap related to its own file, as I do not know which pieces the previous team used, since the lines don't really match up at all.

**Pull request closed without merging**
